version: "3"
services:
  bugme:
    image: monyslim/bugme:1
    restart: always
    depends_on:
      - mysql
    ports:
      - 91:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bugme